// <auto-generated />
using System;
using CasImportaciones.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CasImportaciones.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CasImportacionesDbContext))]
    [Migration("20201114045219_InitialModel")]
    partial class InitialModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CasImportaciones.Core.Domain.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar(80)")
                        .HasMaxLength(80);

                    b.HasKey("IdCategoria");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("CasImportaciones.Core.Domain.Inventario", b =>
                {
                    b.Property<int>("IdInventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cantidad")
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<string>("Referencia")
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15);

                    b.HasKey("IdInventario");

                    b.ToTable("Inventario");
                });

            modelBuilder.Entity("CasImportaciones.Core.Domain.OrdenCompra", b =>
                {
                    b.Property<int>("IdCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("datetime");

                    b.Property<string>("Referencia")
                        .HasColumnType("text");

                    b.HasKey("IdCompra");

                    b.ToTable("OrdenCompra");
                });

            modelBuilder.Entity("CasImportaciones.Core.Domain.OrdenVenta", b =>
                {
                    b.Property<int>("IdVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasMaxLength(80);

                    b.Property<DateTime>("FechaVenta")
                        .HasColumnType("datetime");

                    b.Property<double>("ValorTotal")
                        .HasColumnType("double");

                    b.HasKey("IdVenta");

                    b.ToTable("OrdenVenta");
                });

            modelBuilder.Entity("CasImportaciones.Core.Domain.Persona", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cedula")
                        .HasColumnType("int");

                    b.Property<string>("Correo")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30);

                    b.Property<double>("Direccion")
                        .HasColumnType("double")
                        .HasMaxLength(30);

                    b.Property<string>("PrimerApellido")
                        .HasColumnType("varchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("PrimerNombre")
                        .HasColumnType("varchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("SegundoApellido")
                        .HasColumnType("varchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("SegundoNombre")
                        .HasColumnType("varchar(40)")
                        .HasMaxLength(40);

                    b.Property<double>("Telefono")
                        .HasColumnType("double");

                    b.HasKey("IdUsuario");

                    b.ToTable("Persona");
                });

            modelBuilder.Entity("CasImportaciones.Core.Domain.Producto", b =>
                {
                    b.Property<string>("Refertencia")
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("Marca")
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15);

                    b.Property<double>("Precio")
                        .HasColumnType("double");

                    b.HasKey("Refertencia");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("CasImportaciones.Core.Domain.Proveedor", b =>
                {
                    b.Property<int>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ciudad")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Direccion")
                        .HasColumnType("varchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("NombreProveedor")
                        .HasColumnType("varchar(40)")
                        .HasMaxLength(40);

                    b.Property<double>("Telefono")
                        .HasColumnType("double");

                    b.HasKey("IdProveedor");

                    b.ToTable("Proveedor");
                });

            modelBuilder.Entity("CasImportaciones.Core.Domain.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.HasKey("IdRol");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("CasImportaciones.Core.Domain.TipoIdentificacion", b =>
                {
                    b.Property<int>("IdTipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("varchar(40)")
                        .HasMaxLength(40);

                    b.HasKey("IdTipo");

                    b.ToTable("TipoIdentificacion");
                });
#pragma warning restore 612, 618
        }
    }
}
